package com.lifeos.backend.task.domain.enums;

/**
 * Audit log type.
 *
 * MutationHistory should use this to explain what happened.
 */
public enum MutationType {

    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_PAUSED,
    TEMPLATE_RESUMED,
    TEMPLATE_ARCHIVED,
    TEMPLATE_RESTORED,

    INSTANCE_CREATED,
    INSTANCE_SPAWNED,
    INSTANCE_STARTED,
    INSTANCE_COMPLETED,
    INSTANCE_REOPENED,
    INSTANCE_OVERDUE,
    INSTANCE_ROLLED_OVER,
    INSTANCE_MISSED,
    INSTANCE_RESCHEDULED,
    INSTANCE_SKIPPED,
    INSTANCE_PAUSED,
    INSTANCE_RESUMED,
    INSTANCE_ARCHIVED,
    INSTANCE_RESTORED,
    INSTANCE_CANCELLED,

    DONE_CLEARED,
    DONE_RESTORED,

    REMINDER_ADDED,
    REMINDER_UPDATED,
    REMINDER_REMOVED,

    LINKED_SCHEDULE_CHANGED,
    PRIORITY_CHANGED,
    CATEGORY_CHANGED,
    RECURRENCE_CHANGED,

    SYSTEM_AUTO_SPAWNED,
    SYSTEM_AUTO_OVERDUE,
    SYSTEM_AUTO_MISSED,
    SYSTEM_AUTO_ROLLED_OVER
}